# Generated by Django 4.1.1 on 2022-09-26 12:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=75,
                scale=0.5,
                size=[500, 300],
                upload_to="uploads/",
            ),
        ),
    ]
